### ISSUE TITLE
Sea of Thieves - cannot open any mesh file.

### ISSUE THREAD

**Issue by xlifi** [4sval/FModel#291] opened 2022-06-16 12:54 UTC
### Game

Sea of Thieves

### Error

```shell
Console:
[ERR] One or more errors occurred. (Failed to decompress LZ4 data (Expected: 65536, Result: -1))
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

Log:
2022-06-16 22:40:28 [FModel] [INF] User DOUBLE-CLICKED to extract 'Athena/Content/Models/Characters/NPCs/npc_hunters_call/npc_hunters_call_merrick.uasset'
2022-06-16 22:40:28 [FModel] [ERR] System.AggregateException: One or more errors occurred. (Failed to decompress LZ4 data (Expected: 65536, Result: -1))
 ---> System.IO.FileLoadException: Failed to decompress LZ4 data (Expected: 65536, Result: -1)
   at CUE4Parse.Compression.Compression.Decompress(Byte[] compressed, Int32 compressedOffset, Int32 compressedSize, Byte[] uncompressed, Int32 uncompressedOffset, Int32 uncompressedSize, CompressionMethod method, FArchive reader)
   at CUE4Parse.UE4.Pak.PakFileReader.Extract(VfsEntry entry)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at CUE4Parse.FileProvider.GameFile.CreateReaderAsync()
   at CUE4Parse.FileProvider.AbstractFileProvider.LoadPackageAsync(GameFile file)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at FModel.ViewModels.CUE4ParseViewModel.Extract(String fullPath, Boolean addNewTab, Boolean bulkSave)
   at FModel.ViewModels.CUE4ParseViewModel.ExtractSelected(CancellationToken cancellationToken, IEnumerable`1 assetItems)
   at FModel.MainWindow.<>c__DisplayClass18_0.<OnAssetsListMouseDoubleClick>b__0(CancellationToken cancellationToken)
   at FModel.ViewModels.ThreadWorkerViewModel.<>c__DisplayClass20_0.<ProcessQueues>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FModel.ViewModels.ThreadWorkerViewModel.ProcessQueues()
```

### Reproduction steps

1. Open Sea of Thieves paks
2. Use `0x9CE69870E6FA70E820AB073E991889ECB244B34AAF6A2321C47FF2597A2EF90E` AES key
3. Open any asset with mesh (I used npc_hunters_call_merrick.uasset)

**Comment by xlifi** [comment] 2022-06-17 13:08
closing issue because no one cares about any game that is not fortnite

**Comment by iAmAsval** [comment] 2022-06-17 13:40
that is not true

there are multiple reasons why no contributor responds, here is a few of them

- it's only been opened yesterday, on a business day (probably a bit longer on discord)
- I personally don't have that game
- fully belongs to [CUE4Parse](https://github.com/FabianFG/CUE4Parse)
- sounds like it's only related to meshes but is probably not

Furthermore, if you guys only want mesh-related assets on a game that is not fortnite, we always recommend using [UEViewer](https://github.com/gildor2/UEViewer) instead as it's faster and support more games

---

<sub>I'd also add that, although I love fixing issues, I do not enjoy fixing mesh-related issues on any game as it's pretty boring to me because it's often customized by the studio for whatever reason we don't know and the data inside doesn't interest me</sub>

**Comment by mrdiploben** [comment] 2022-06-21 16:35
As said above, this software is made for anything on unreal engine due to how the decryption works on UE. If you want one for sea of thieves get a dev team to do it for you.

If someone could close this it would be highly appreciated as it is no longer relevant.

**Comment by GMatrixGames** [comment] 2022-06-21 16:51
Sea of Thieves is on Unreal Engine. The issue is due to improper LZ4 decompression

**Comment by GMatrixGames** [comment] 2022-12-20 02:13
Finally after looking into it, it's a very simple thing to fix.

JUST PUT THE AES KEY...

Sea of Thieves AES: 0x37A0BC3DC2E01D9EB4923CA266A5701F56A4802347F07927FC3FC25C93B31B50

**Closed by GMatrixGames** 2022-12-20 02:13 UTC
Labels: bug

**Comment by xlifi** [comment] 2022-12-20 15:15
since when sea of thieves changed aes key?

**Comment by xlifi** [comment] 2022-12-20 15:28
> Finally after looking into it, it's a very simple thing to fix.
> 
> JUST PUT THE AES KEY...
> 
> Sea of Thieves AES: 0x37A0BC3DC2E01D9EB4923CA266A5701F56A4802347F07927FC3FC25C93B31B50

It doesn't work for me with this aes key too.

`[ERR] CUE4Parse.Compression.OodleException: Oodle decompression failed with result 0
   at CUE4Parse.Compression.Oodle.Decompress(Byte[] compressed, Int32 compressedOffset, Int32 compressedSize, Byte[] uncompressed, Int32 uncompressedOffset, Int32 uncompressedSize, FArchive reader)`

**Comment by GMatrixGames** [comment] 2022-12-20 15:30
Do you have your game set to SOT, because I just tested it yesterday and it works perfectly fine

**Comment by xlifi** [comment] 2022-12-21 05:27
> Do you have your game set to SOT, because I just tested it yesterday and it works perfectly fine ![image](https://user-images.githubusercontent.com/25112532/208705681-ffd79726-7228-48f8-920b-89dc7fa6d02d.png)

yes, for whatever reason it changed from ue4_seaofthieves to ue4_latest

When i chose ue4_seaofthieves it did not open 3d viewer, however

**Comment by GMatrixGames** [comment] 2022-12-21 14:33
What is the file you're trying to open?

**Comment by xlifi** [comment] 2022-12-22 11:23
> What is the file you're trying to open?

any .uasset file in Athena/Content/Models folder

**Comment by xlifi** [comment] 2022-12-22 11:26
I just dont understand how to load the model into 3d viewer

**Comment by GMatrixGames** [comment] 2022-12-22 14:30
Wait for the next FModel update, and it'll be fixed.

**Comment by xlifi** [comment] 2022-12-22 17:25
> sounds like it's only related to meshes but is probably not

Its related not only to meshes. Animations fail to export: 
`[ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at CUE4Parse.UE4.Assets.Exports.Animation.UAnimSequence.GetNumTracks()`
